### ISSUE TITLE
chat/text box tweaks

### ISSUE THREAD

**Issue by midget3111** [trigg/Rebuttal#47]
if possible, pad text box from bottom of window,
maybe make it double height too?
fix send button so it doesn't overlap with other icons.

**Comment by trigg** [comment]
Buttons should now not overlap send/text

**Comment by midget3111** [comment]
> Buttons should now not overlap send/text

![Screenshot from 2021-05-18 14-05-52](https://user-images.githubusercontent.com/964775/118653912-eb684000-b7df-11eb-95f8-bcdfad37d051.png)
